export function getDomRefs() {
  return Object.freeze({
    legend: document.getElementById("legend"),
    heatCB: document.getElementById("cb-heat"),
    labelsCB: document.getElementById("cb-labels"),
    pointsCB: document.getElementById("cb-points"),
    toast: document.getElementById("toast"),
    fab: document.getElementById("btn-gen"),
    loadedBadge: document.getElementById("loaded-badge"),
    loadedInfo: document.getElementById("loaded-info"),
    gridSize: document.getElementById("grid-size"),
    gridOut: document.getElementById("grid-out"),
    menuBtn: document.getElementById("btn-menu"),
    panel: document.getElementById("panel"),
    locateBtn: document.getElementById("btn-locate"),
    btnAll: document.getElementById("btn-all"),
    btnNone: document.getElementById("btn-none"),
    filterInput: document.getElementById("filter-input"),
    btnSave: document.getElementById("btn-save"),
    btnLoad: document.getElementById("btn-load"),
    btnHistory: document.getElementById("btn-history"),
    btnAbout: document.getElementById("btn-about"),
    fileInput: document.getElementById("file-input"),
    useLoaded: document.getElementById("use-loaded"),
    aboutBackdrop: document.getElementById("about-backdrop"),
    aboutClose: document.getElementById("about-close"),
    historyBackdrop: document.getElementById("history-backdrop"),
    historyClose: document.getElementById("history-close"),
    historyList: document.getElementById("history-list"),
    historyEmpty: document.getElementById("history-empty"),
    btnHistoryClear: document.getElementById("btn-history-clear"),
  });
}
